In [15]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [16]:
x,y = make_classification(n_samples=10000, n_features=10, n_informative=3)
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state=42)

In [17]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(xtrain, ytrain)

accuracy_score(ytest, dt.predict(xtest))

0.9165

Bagging


In [23]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42,
)

In [24]:
bag.fit(xtrain, ytrain)

,"estimator estimator: object, default=NoneThe base estimator to fit on random subsets of the dataset.If None, then the base estimator is a:class:`~sklearn.tree.DecisionTreeClassifier`... versionadded:: 1.2 `base_estimator` was renamed to `estimator`.",DecisionTreeClassifier()
,"n_estimators n_estimators: int, default=10The number of base estimators in the ensemble.",500
,"max_samples max_samples: int or float, default=NoneThe number of samples to draw from X to train each base estimator (withreplacement by default, see `bootstrap` for more details).- If None, then draw `X.shape[0]` samples irrespective of `sample_weight`.- If int, then draw `max_samples` samples.- If float, then draw `max_samples * X.shape[0]` unweighted samples or `max_samples * sample_weight.sum()` weighted samples.",0.25
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random resampling of the original dataset(sample wise and feature wise).If the base estimator accepts a `random_state` attribute, a differentseed is generated for each instance in the ensemble.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"max_features max_features: int or float, default=1.0The number of features to draw from X to train each base estimator (without replacement by default, see `bootstrap_features` for moredetails).- If int, then draw `max_features` features.- If float, then draw `max(1, int(max_features * n_features_in_))` features.",1.0
,"bootstrap bootstrap: bool, default=TrueWhether samples are drawn with replacement. If False, sampling withoutreplacement is performed. If fitting with `sample_weight`, it isstrongly recommended to choose True, as only drawing with replacementwill ensure the expected frequency semantics of `sample_weight`.",True
,"bootstrap_features bootstrap_features: bool, default=FalseWhether features are drawn with replacement.",False
,"oob_score oob_score: bool, default=FalseWhether to use out-of-bag samples to estimatethe generalization error. Only available if bootstrap=True.",False
,"warm_start warm_start: bool, default=FalseWhen set to True, reuse the solution of the previous call to fitand add more estimators to the ensemble, otherwise, just fita whole new ensemble. See :term:`the Glossary <warm_start>`... versionadded:: 0.17 *warm_start* constructor parameter.",False
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for both :meth:`fit` and:meth:`predict`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"verbose verbose: int, default=0Controls the verbosity when fitting and predicting.",0


In [25]:
accuracy_score(ytest , bag.predict(xtest))

0.9365

In [29]:
bag.estimators_samples_

[array([2523, 3113, 7114, ..., 4291, 4472, 3620],
       shape=(2000,), dtype=int32),
 array([4782,  663, 7155, ..., 5963,  495, 1767],
       shape=(2000,), dtype=int32),
 array([5462, 6574, 4896, ..., 3979, 7827,   37],
       shape=(2000,), dtype=int32),
 array([2848, 2629, 1591, ..., 7723, 1314, 1565],
       shape=(2000,), dtype=int32),
 array([3821, 6494, 1606, ..., 5686, 7870, 2558],
       shape=(2000,), dtype=int32),
 array([2261, 7922, 3649, ..., 4478, 6286, 6943],
       shape=(2000,), dtype=int32),
 array([ 652, 1676, 2291, ..., 2723, 7007, 6344],
       shape=(2000,), dtype=int32),
 array([2478, 4107, 1958, ..., 7979, 5695, 7854],
       shape=(2000,), dtype=int32),
 array([5800, 3548, 6540, ..., 3899,  831,   55],
       shape=(2000,), dtype=int32),
 array([5256, 7181, 3409, ..., 5286, 7535, 1335],
       shape=(2000,), dtype=int32),
 array([2675, 2834, 3817, ..., 1726, 2323, 7642],
       shape=(2000,), dtype=int32),
 array([3236, 7607, 4600, ...,  445, 7501, 6604],
    

In [27]:
bag.estimators_features_

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),


Bagging with SVM


In [30]:
bag = BaggingClassifier(
    estimator=SVC(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)

In [31]:
bag.fit(xtrain, ytrain)

,"estimator estimator: object, default=NoneThe base estimator to fit on random subsets of the dataset.If None, then the base estimator is a:class:`~sklearn.tree.DecisionTreeClassifier`... versionadded:: 1.2 `base_estimator` was renamed to `estimator`.",SVC()
,"n_estimators n_estimators: int, default=10The number of base estimators in the ensemble.",500
,"max_samples max_samples: int or float, default=NoneThe number of samples to draw from X to train each base estimator (withreplacement by default, see `bootstrap` for more details).- If None, then draw `X.shape[0]` samples irrespective of `sample_weight`.- If int, then draw `max_samples` samples.- If float, then draw `max_samples * X.shape[0]` unweighted samples or `max_samples * sample_weight.sum()` weighted samples.",0.25
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random resampling of the original dataset(sample wise and feature wise).If the base estimator accepts a `random_state` attribute, a differentseed is generated for each instance in the ensemble.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"max_features max_features: int or float, default=1.0The number of features to draw from X to train each base estimator (without replacement by default, see `bootstrap_features` for moredetails).- If int, then draw `max_features` features.- If float, then draw `max(1, int(max_features * n_features_in_))` features.",1.0
,"bootstrap bootstrap: bool, default=TrueWhether samples are drawn with replacement. If False, sampling withoutreplacement is performed. If fitting with `sample_weight`, it isstrongly recommended to choose True, as only drawing with replacementwill ensure the expected frequency semantics of `sample_weight`.",True
,"bootstrap_features bootstrap_features: bool, default=FalseWhether features are drawn with replacement.",False
,"oob_score oob_score: bool, default=FalseWhether to use out-of-bag samples to estimatethe generalization error. Only available if bootstrap=True.",False
,"warm_start warm_start: bool, default=FalseWhen set to True, reuse the solution of the previous call to fitand add more estimators to the ensemble, otherwise, just fita whole new ensemble. See :term:`the Glossary <warm_start>`... versionadded:: 0.17 *warm_start* constructor parameter.",False
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for both :meth:`fit` and:meth:`predict`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"verbose verbose: int, default=0Controls the verbosity when fitting and predicting.",0


In [32]:
accuracy_score(ytest, bag.predict(xtest))

0.922

Pasting

In [33]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=False,   #sampling without reokacement 
    random_state=42,
    verbose=1,  
    n_jobs=-1  #devide the task in all cores of cpu in my system
)

In [34]:
bag.fit(xtrain, ytrain)
accuracy_score(ytest, bag.predict(xtest))

[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   2 out of  12 | elapsed:   14.6s remaining:  1.2min
[Parallel(n_jobs=12)]: Done  12 out of  12 | elapsed:   14.7s finished
[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   2 out of  12 | elapsed:    0.0s remaining:    0.6s
[Parallel(n_jobs=12)]: Done  12 out of  12 | elapsed:    0.2s finished


0.9365

Random Subsoaces

In [38]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=1.0,
    bootstrap=False,
    max_features=0.5, # column sampling 
    bootstrap_features=True,
    random_state=42,
    n_jobs=-1
)

In [39]:
bag.fit(xtrain, ytrain)
accuracy_score(ytest, bag.predict(xtest))

0.9295

In [40]:
bag.estimators_samples_

[array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([   0,    1,    2, ..., 7997, 7998, 7999], shape=(8000,)),
 array([  

In [41]:
bag.estimators_features_

[array([9, 2, 9, 7, 7], dtype=int32),
 array([7, 3, 7, 3, 9], dtype=int32),
 array([6, 0, 7, 7, 9], dtype=int32),
 array([0, 5, 7, 4, 1], dtype=int32),
 array([6, 9, 6, 3, 3], dtype=int32),
 array([5, 2, 1, 2, 7], dtype=int32),
 array([3, 2, 1, 5, 2], dtype=int32),
 array([6, 2, 8, 2, 5], dtype=int32),
 array([8, 4, 4, 3, 2], dtype=int32),
 array([8, 1, 8, 9, 0], dtype=int32),
 array([3, 2, 9, 8, 4], dtype=int32),
 array([4, 7, 8, 6, 7], dtype=int32),
 array([3, 9, 4, 8, 6], dtype=int32),
 array([0, 9, 6, 7, 4], dtype=int32),
 array([0, 8, 2, 0, 2], dtype=int32),
 array([8, 4, 6, 6, 8], dtype=int32),
 array([7, 7, 2, 0, 3], dtype=int32),
 array([8, 4, 2, 8, 1], dtype=int32),
 array([7, 4, 2, 8, 6], dtype=int32),
 array([8, 1, 5, 0, 2], dtype=int32),
 array([5, 8, 8, 3, 0], dtype=int32),
 array([4, 6, 2, 7, 7], dtype=int32),
 array([1, 5, 2, 7, 1], dtype=int32),
 array([8, 8, 6, 9, 9], dtype=int32),
 array([1, 4, 2, 3, 7], dtype=int32),
 array([4, 1, 3, 1, 4], dtype=int32),
 array([8, 8

Random patches

In [42]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25, #row sampling 
    bootstrap=True,
    max_features=0.5, # column sampling 
    bootstrap_features=True,
    random_state=42,
    n_jobs=-1
)

In [43]:
bag.fit(xtrain, ytrain)
accuracy_score(ytest, bag.predict(xtest))

0.92

OOB Score - around 37% rows are not used to train any decision tree =. therefore they are called "Out Of Bag"  

In [44]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    oob_score=True,
    random_state=42
)

In [46]:
bag.fit(xtrain, ytrain)

,"estimator estimator: object, default=NoneThe base estimator to fit on random subsets of the dataset.If None, then the base estimator is a:class:`~sklearn.tree.DecisionTreeClassifier`... versionadded:: 1.2 `base_estimator` was renamed to `estimator`.",DecisionTreeClassifier()
,"n_estimators n_estimators: int, default=10The number of base estimators in the ensemble.",500
,"max_samples max_samples: int or float, default=NoneThe number of samples to draw from X to train each base estimator (withreplacement by default, see `bootstrap` for more details).- If None, then draw `X.shape[0]` samples irrespective of `sample_weight`.- If int, then draw `max_samples` samples.- If float, then draw `max_samples * X.shape[0]` unweighted samples or `max_samples * sample_weight.sum()` weighted samples.",0.25
,"oob_score oob_score: bool, default=FalseWhether to use out-of-bag samples to estimatethe generalization error. Only available if bootstrap=True.",True
,"random_state random_state: int, RandomState instance or None, default=NoneControls the random resampling of the original dataset(sample wise and feature wise).If the base estimator accepts a `random_state` attribute, a differentseed is generated for each instance in the ensemble.Pass an int for reproducible output across multiple function calls.See :term:`Glossary <random_state>`.",42
,"max_features max_features: int or float, default=1.0The number of features to draw from X to train each base estimator (without replacement by default, see `bootstrap_features` for moredetails).- If int, then draw `max_features` features.- If float, then draw `max(1, int(max_features * n_features_in_))` features.",1.0
,"bootstrap bootstrap: bool, default=TrueWhether samples are drawn with replacement. If False, sampling withoutreplacement is performed. If fitting with `sample_weight`, it isstrongly recommended to choose True, as only drawing with replacementwill ensure the expected frequency semantics of `sample_weight`.",True
,"bootstrap_features bootstrap_features: bool, default=FalseWhether features are drawn with replacement.",False
,"warm_start warm_start: bool, default=FalseWhen set to True, reuse the solution of the previous call to fitand add more estimators to the ensemble, otherwise, just fita whole new ensemble. See :term:`the Glossary <warm_start>`... versionadded:: 0.17 *warm_start* constructor parameter.",False
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel for both :meth:`fit` and:meth:`predict`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"verbose verbose: int, default=0Controls the verbosity when fitting and predicting.",0


In [49]:
bag.oob_score_  # tell about accuracy 

0.939625

In [48]:
accuracy_score(ytest, bag.predict(xtest))

0.9365

BAGGING TIPS:

    Bagging generally gives better results than Pasting.


    Good results come around the 25% to 50% row sampling mark.


    Random Patches and subspaces should be used while dealing with high dimensional data.


    To find the correct hyperparameter values we can do GridSearchCV/RandomSearchCV.



Apply GridSearchCV

In [50]:
from sklearn.model_selection import GridSearchCV

In [51]:
parameters = {
    'n_estimators': [50, 100, 500],
    'max_samples':[0.1, 0.4, 0.7, 1.0],
    'bootstrap':[True, False],
    'max_features': [0.1, 0.4, 0.7, 1.0]
}

In [52]:
search = GridSearchCV(BaggingClassifier(), parameters, cv = 5)

In [53]:
search.fit(xtrain, ytrain)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",BaggingClassifier()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'bootstrap': [True, False], 'max_features': [0.1, 0.4, ...], 'max_samples': [0.1, 0.4, ...], 'n_estimators': [50, 100, ...]}"
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",None
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",None
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"verbose verbo

In [54]:
search.best_score_

np.float64(0.94275)

In [55]:
search.best_params_

{'bootstrap': True,
 'max_features': 0.7,
 'max_samples': 0.7,
 'n_estimators': 500}